/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.File;
import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        Bitmap img = new Bitmap("bw","Test1","Test");
        img.transfrom("multiFilter","Test2","Test");
        img.transfrom("Zoom","Test3","Test");
        img.transfrom("BlueDots","Test4","Test");
        img.transfrom("halfAndHalf","Test5","Test");

    }
}
